apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/infrastructure/certmanager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: managed-cert-manager
  path: ./base/infrastructure/capi-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-providers
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: capi-operator
  path: ./base/infrastructure/capi-providers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin-capi-manifests
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: capi-providers
  path: ./cluster/kind/admin-capi-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kind-cilium
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: admin-capi-manifests
  path: ./base/infrastructure/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-flux-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: kind-cilium
  path: ./base/infrastructure/flux-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: capiquickstart-kubeconfig
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: managed-flux-operator
  path: ./base/infrastructure/certmanager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: managed-cert-manager
#   namespace: flux-system
# spec:
#   interval: 10m
#   dependsOn:
#     - name: managed-flux-operator # Won't run until the operator pod is alive to handle webhooks
#   path: ./clusters/managed-cluster/sync-root
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   kubeConfig:
#     secretRef:
#       name: capiquickstart-kubeconfig
#   wait: true