apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# List all the yaml orchestration files sitting inside this directory
resources:
  - cluster-sync.yaml # The manifest holding your staging sequence
  - admin-capi-manifests/